name: Node CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  # install dependencies
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project    
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-dependencies
          path: node_modules
          retention-days: 1
  # generate build
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Download dependencies
        uses: actions/download-artifact@v2
        with:
          name: app-dependencies


      - name: Generate build
        run: npm run build
  # run tests
  test:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [12.x, 14.x]    
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Download dependencies
        uses: actions/download-artifact@v2
        with:
          name: app-dependencies


      - name: npm test
        run: npm test
        env:
          CI: true
